### ISSUE TITLE
How to use in a project folder

### ISSUE THREAD

**Issue by f-liva** [nikosdion/joomlatypehints#4]
Hello

I can't install the package with composer require nikosdion/joomla_typehints

How I can install in a project folder and use directly from here?

**Comment by nikosdion** [comment]
Clone the Git repository. You do know what Git is and how it works, right...?

**Comment by f-liva** [comment]
I want to use as a project dependency and not cloning the repo, installing its dependencies and run the php file

Look at Laravel IDE Helper. Why don't do a thing like that?

**Comment by nikosdion** [comment]
There is only one Joomla. There are infinite Laravel applications. I only need to make a set of typehints per Joomla version family, once, and reference it in all my projects. Therefore I wrote a minimum viable solution. Simple!

If you feel like throwing away everything I’ve written and creating your own super complicated solution just because you have too much time on your hands, cool, best of luck and have a nice day. But don’t ask that I do it for you and for free because I have neither a need for it nor the time to do it. Also, this solution here works really great for years. If it ain’t broken don’t fix it. 

Does this answer cover you?
